#define OCAML_STACK_WOSIZE                64
#define OCAML_STATIC_HEAP_WOSIZE          12
#define OCAML_DYNAMIC_HEAP_WOSIZE        244
#define OCAML_FLASH_HEAP_WOSIZE          118
#define OCAML_STACK_INITIAL_WOSIZE         5
#define OCAML_RAM_GLOBDATA_NUMBER          0
#define OCAML_FLASH_GLOBDATA_NUMBER       29
#define OCAML_BYTECODE_BSIZE             710
#define OCAML_PRIMITIVE_NUMBER            22
#define OCAML_VIRTUAL_ARCH                32
#define OCAML_STARTING_OOID                1
#define OCAML_NO_FLASH_HEAP                0
#define OCAML_NO_FLASH_GLOBALS             0

#define OCAML_GC_MARK_AND_COMPACT

#include </media/sf_SF2/ml/O2B/omicrob/include/vm/values.h>

#define OCAML_ACC0                        0
#define OCAML_ACC1                        1
#define OCAML_ACC2                        2
#define OCAML_ACC4                        3
#define OCAML_ACC                         4
#define OCAML_PUSH                        5
#define OCAML_PUSHACC1                    6
#define OCAML_PUSHACC2                    7
#define OCAML_PUSHACC3                    8
#define OCAML_PUSHACC4                    9
#define OCAML_PUSHACC5                   10
#define OCAML_PUSHACC6                   11
#define OCAML_PUSHACC7                   12
#define OCAML_PUSHACC                    13
#define OCAML_POP                        14
#define OCAML_ASSIGN                     15
#define OCAML_ENVACC1                    16
#define OCAML_ENVACC2                    17
#define OCAML_ENVACC3                    18
#define OCAML_PUSHENVACC1                19
#define OCAML_PUSHENVACC3                20
#define OCAML_APPLY1                     21
#define OCAML_APPLY2                     22
#define OCAML_APPLY3                     23
#define OCAML_APPTERM1                   24
#define OCAML_APPTERM2                   25
#define OCAML_APPTERM3                   26
#define OCAML_RETURN                     27
#define OCAML_RESTART                    28
#define OCAML_GRAB                       29
#define OCAML_CLOSURE_1B                 30
#define OCAML_CLOSURE_2B                 31
#define OCAML_CLOSUREREC_1B              32
#define OCAML_PUSHOFFSETCLOSURE0         33
#define OCAML_GETFLASHGLOBAL_1B          34
#define OCAML_PUSHGETFLASHGLOBAL_1B      35
#define OCAML_MAKEBLOCK2                 36
#define OCAML_GETFIELD0                  37
#define OCAML_GETFIELD1                  38
#define OCAML_GETFIELD2                  39
#define OCAML_GETBYTESCHAR               40
#define OCAML_BRANCH_1B                  41
#define OCAML_BRANCH_2B                  42
#define OCAML_BRANCHIF_1B                43
#define OCAML_BRANCHIFNOT_1B             44
#define OCAML_RAISE                      45
#define OCAML_CHECK_SIGNALS              46
#define OCAML_C_CALL1                    47
#define OCAML_C_CALL2                    48
#define OCAML_C_CALL3                    49
#define OCAML_C_CALL4                    50
#define OCAML_C_CALL5                    51
#define OCAML_CONST0                     52
#define OCAML_CONST1                     53
#define OCAML_CONSTINT_1B                54
#define OCAML_PUSHCONST0                 55
#define OCAML_PUSHCONSTINT_1B            56
#define OCAML_PUSHCONSTINT_4B            57
#define OCAML_ADDINT                     58
#define OCAML_SUBINT                     59
#define OCAML_MULINT                     60
#define OCAML_EQ                         61
#define OCAML_NEQ                        62
#define OCAML_LTINT                      63
#define OCAML_GTINT                      64
#define OCAML_OFFSETINT_1B               65
#define OCAML_BLTINT_1B                  66
#define OCAML_BGTINT_1B                  67
#define OCAML_STOP                       68

value ocaml_stack[OCAML_STACK_WOSIZE];
value ocaml_ram_heap[OCAML_STATIC_HEAP_WOSIZE + OCAML_DYNAMIC_HEAP_WOSIZE];
value ocaml_ram_global_data[OCAML_RAM_GLOBDATA_NUMBER];

PROGMEM value const ocaml_flash_heap[OCAML_FLASH_HEAP_WOSIZE] = {
  /*   0 */  Make_header(0, 0, Color_white),
  /*   1 */  Make_header(2, Object_tag, Color_white),
  /*   2 */  Val_flash_block(&ocaml_flash_heap[5]),
  /*   3 */  Val_int(-1),
  /*   4 */  Make_header(4, String_tag, Color_white),
  /*   5 */  Make_string_data('O', 'u', 't', '_'),
  /*   6 */  Make_string_data('o', 'f', '_', 'm'),
  /*   7 */  Make_string_data('e', 'm', 'o', 'r'),
  /*   8 */  Make_string_data('y', '\0', '\0', '\2'),
  /*   9 */  Make_header(2, Object_tag, Color_white),
  /*  10 */  Val_flash_block(&ocaml_flash_heap[13]),
  /*  11 */  Val_int(-3),
  /*  12 */  Make_header(2, String_tag, Color_white),
  /*  13 */  Make_string_data('F', 'a', 'i', 'l'),
  /*  14 */  Make_string_data('u', 'r', 'e', '\0'),
  /*  15 */  Make_header(2, Object_tag, Color_white),
  /*  16 */  Val_flash_block(&ocaml_flash_heap[19]),
  /*  17 */  Val_int(-4),
  /*  18 */  Make_header(5, String_tag, Color_white),
  /*  19 */  Make_string_data('I', 'n', 'v', 'a'),
  /*  20 */  Make_string_data('l', 'i', 'd', '_'),
  /*  21 */  Make_string_data('a', 'r', 'g', 'u'),
  /*  22 */  Make_string_data('m', 'e', 'n', 't'),
  /*  23 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  24 */  Make_header(2, Object_tag, Color_white),
  /*  25 */  Val_flash_block(&ocaml_flash_heap[28]),
  /*  26 */  Val_int(-6),
  /*  27 */  Make_header(5, String_tag, Color_white),
  /*  28 */  Make_string_data('D', 'i', 'v', 'i'),
  /*  29 */  Make_string_data('s', 'i', 'o', 'n'),
  /*  30 */  Make_string_data('_', 'b', 'y', '_'),
  /*  31 */  Make_string_data('z', 'e', 'r', 'o'),
  /*  32 */  Make_string_data('\0', '\0', '\0', '\3'),
  /*  33 */  Make_header(2, Object_tag, Color_white),
  /*  34 */  Val_flash_block(&ocaml_flash_heap[37]),
  /*  35 */  Val_int(-9),
  /*  36 */  Make_header(4, String_tag, Color_white),
  /*  37 */  Make_string_data('S', 't', 'a', 'c'),
  /*  38 */  Make_string_data('k', '_', 'o', 'v'),
  /*  39 */  Make_string_data('e', 'r', 'f', 'l'),
  /*  40 */  Make_string_data('o', 'w', '\0', '\1'),
  /*  41 */  Make_header(1, Closure_tag, Color_white),
  /*  42 */  Val_codeptr(528),
  /*  43 */  Make_header(1, Closure_tag, Color_white),
  /*  44 */  Val_codeptr(554),
  /*  45 */  Make_header(1, Closure_tag, Color_white),
  /*  46 */  Val_codeptr(579),
  /*  47 */  Make_header(1, Closure_tag, Color_white),
  /*  48 */  Val_codeptr(594),
  /*  49 */  Make_header(1, Closure_tag, Color_white),
  /*  50 */  Val_codeptr(472),
  /*  51 */  Make_header(6, String_tag, Color_white),
  /*  52 */  Make_string_data('S', 't', 'r', 'i'),
  /*  53 */  Make_string_data('n', 'g', '.', 's'),
  /*  54 */  Make_string_data('u', 'b', ' ', '/'),
  /*  55 */  Make_string_data(' ', 'B', 'y', 't'),
  /*  56 */  Make_string_data('e', 's', '.', 's'),
  /*  57 */  Make_string_data('u', 'b', '\0', '\1'),
  /*  58 */  Make_header(1, Closure_tag, Color_white),
  /*  59 */  Val_codeptr(42),
  /*  60 */  Make_header(1, Closure_tag, Color_white),
  /*  61 */  Val_codeptr(105),
  /*  62 */  Make_header(1, Closure_tag, Color_white),
  /*  63 */  Val_codeptr(53),
  /*  64 */  Make_header(1, Closure_tag, Color_white),
  /*  65 */  Val_codeptr(59),
  /*  66 */  Make_header(1, Closure_tag, Color_white),
  /*  67 */  Val_codeptr(48),
  /*  68 */  Make_header(1, Closure_tag, Color_white),
  /*  69 */  Val_codeptr(122),
  /*  70 */  Make_header(1, Closure_tag, Color_white),
  /*  71 */  Val_codeptr(3),
  /*  72 */  Make_header(1, Closure_tag, Color_white),
  /*  73 */  Val_codeptr(275),
  /*  74 */  Make_header(1, Closure_tag, Color_white),
  /*  75 */  Val_codeptr(291),
  /*  76 */  Make_header(1, Closure_tag, Color_white),
  /*  77 */  Val_codeptr(137),
  /*  78 */  Make_header(1, Closure_tag, Color_white),
  /*  79 */  Val_codeptr(220),
  /*  80 */  Make_header(1, Closure_tag, Color_white),
  /*  81 */  Val_codeptr(9),
  /*  82 */  Make_header(1, Closure_tag, Color_white),
  /*  83 */  Val_codeptr(204),
  /*  84 */  Make_header(1, Closure_tag, Color_white),
  /*  85 */  Val_codeptr(462),
  /*  86 */  Make_header(1, Closure_tag, Color_white),
  /*  87 */  Val_codeptr(427),
  /*  88 */  Make_header(1, Closure_tag, Color_white),
  /*  89 */  Val_codeptr(389),
  /*  90 */  Make_header(1, Closure_tag, Color_white),
  /*  91 */  Val_codeptr(97),
  /*  92 */  Make_header(1, Closure_tag, Color_white),
  /*  93 */  Val_codeptr(171),
  /*  94 */  Make_header(1, String_tag, Color_white),
  /*  95 */  Make_string_data(0x0A, '\0', '\0', '\2'),
  /*  96 */  Make_header(1, Closure_tag, Color_white),
  /*  97 */  Val_codeptr(329),
  /*  98 */  Make_header(1, Closure_tag, Color_white),
  /*  99 */  Val_codeptr(337),
  /* 100 */  Make_header(3, String_tag, Color_white),
  /* 101 */  Make_string_data('S', 't', 'd', 'l'),
  /* 102 */  Make_string_data('i', 'b', '.', 'E'),
  /* 103 */  Make_string_data('x', 'i', 't', '\0'),
  /* 104 */  Make_header(1, String_tag, Color_white),
  /* 105 */  Make_string_data(' ', '\0', '\0', '\2'),
  /* 106 */  Make_header(1, Closure_tag, Color_white),
  /* 107 */  Val_codeptr(232),
  /* 108 */  Make_header(1, Closure_tag, Color_white),
  /* 109 */  Val_codeptr(254),
  /* 110 */  Make_header(1, Closure_tag, Color_white),
  /* 111 */  Val_codeptr(249),
  /* 112 */  Make_header(5, String_tag, Color_white),
  /* 113 */  Make_string_data('T', 'i', 'm', 'e'),
  /* 114 */  Make_string_data('r', ' ', 'i', 'n'),
  /* 115 */  Make_string_data('i', 't', ' ', 'f'),
  /* 116 */  Make_string_data('a', 'i', 'l', 'e'),
  /* 117 */  Make_string_data('d', '\0', '\0', '\2')
};

PROGMEM value const ocaml_initial_static_heap[OCAML_STATIC_HEAP_WOSIZE] = {
  /*  0 */  Make_header(4, 0, Color_white),
  /*  1 */  Val_flash_block(&ocaml_flash_heap[97]),
  /*  2 */  Val_flash_block(&ocaml_flash_heap[85]),
  /*  3 */  Val_flash_block(&ocaml_flash_heap[99]),
  /*  4 */  Val_flash_block(&ocaml_flash_heap[87]),
  /*  5 */  Make_header(2, Object_tag, Color_white),
  /*  6 */  Val_flash_block(&ocaml_flash_heap[101]),
  /*  7 */  Val_unit,
  /*  8 */  Make_header(3, 0, Color_white),
  /*  9 */  Val_int(6),
  /* 10 */  Val_flash_block(&ocaml_flash_heap[73]),
  /* 11 */  Val_flash_block(&ocaml_flash_heap[109])
};

PROGMEM value const ocaml_initial_stack[OCAML_STACK_INITIAL_WOSIZE] = {
  /* 0 */  Val_flash_block(&ocaml_flash_heap[42]),
  /* 1 */  Val_flash_block(&ocaml_flash_heap[44]),
  /* 2 */  Val_flash_block(&ocaml_flash_heap[46]),
  /* 3 */  Val_flash_block(&ocaml_flash_heap[48]),
  /* 4 */  Val_flash_block(&ocaml_flash_heap[50])
};

PROGMEM value const ocaml_flash_global_data[OCAML_FLASH_GLOBDATA_NUMBER] = {
  /*  0 */  Val_flash_block(&ocaml_flash_heap[16]),
  /*  1 */  Val_flash_block(&ocaml_flash_heap[52]),
  /*  2 */  Val_flash_block(&ocaml_flash_heap[59]),
  /*  3 */  Val_flash_block(&ocaml_flash_heap[61]),
  /*  4 */  Val_flash_block(&ocaml_flash_heap[63]),
  /*  5 */  Val_flash_block(&ocaml_flash_heap[65]),
  /*  6 */  Val_flash_block(&ocaml_flash_heap[67]),
  /*  7 */  Val_flash_block(&ocaml_flash_heap[69]),
  /*  8 */  Val_flash_block(&ocaml_flash_heap[71]),
  /*  9 */  Val_flash_block(&ocaml_flash_heap[73]),
  /* 10 */  Val_flash_block(&ocaml_flash_heap[75]),
  /* 11 */  Val_flash_block(&ocaml_flash_heap[77]),
  /* 12 */  Val_flash_block(&ocaml_flash_heap[79]),
  /* 13 */  Val_flash_block(&ocaml_flash_heap[81]),
  /* 14 */  Val_flash_block(&ocaml_flash_heap[83]),
  /* 15 */  Val_flash_block(&ocaml_flash_heap[85]),
  /* 16 */  Val_flash_block(&ocaml_flash_heap[87]),
  /* 17 */  Val_flash_block(&ocaml_flash_heap[89]),
  /* 18 */  Val_flash_block(&ocaml_flash_heap[91]),
  /* 19 */  Val_flash_block(&ocaml_flash_heap[93]),
  /* 20 */  Val_flash_block(&ocaml_flash_heap[95]),
  /* 21 */  Val_static_block(&ocaml_ram_heap[1]),
  /* 22 */  Val_static_block(&ocaml_ram_heap[6]),
  /* 23 */  Val_flash_block(&ocaml_flash_heap[105]),
  /* 24 */  Val_flash_block(&ocaml_flash_heap[107]),
  /* 25 */  Val_flash_block(&ocaml_flash_heap[95]),
  /* 26 */  Val_static_block(&ocaml_ram_heap[9]),
  /* 27 */  Val_flash_block(&ocaml_flash_heap[111]),
  /* 28 */  Val_flash_block(&ocaml_flash_heap[113])
};

value acc = Val_unit;
value env = Val_unit;

#define OCAML_Out_of_memory        Val_flash_block(&ocaml_flash_heap[2])
#define OCAML_Failure              Val_flash_block(&ocaml_flash_heap[10])
#define OCAML_Invalid_argument     Val_flash_block(&ocaml_flash_heap[16])
#define OCAML_Division_by_zero     Val_flash_block(&ocaml_flash_heap[25])
#define OCAML_Stack_overflow       Val_flash_block(&ocaml_flash_heap[34])

#define OCAML_atom0                Val_flash_block(&ocaml_flash_heap[1])

PROGMEM opcode_t const ocaml_bytecode[OCAML_BYTECODE_BSIZE] = {
  /*   0 */  OCAML_BRANCH_2B, 2, 93,
  /*   3 */  OCAML_ACC0,
  /*   4 */  OCAML_C_CALL1, 0,
  /*   6 */  OCAML_RETURN, 1,
  /*   8 */  OCAML_RESTART,
  /*   9 */  OCAML_GRAB, 1,
  /*  11 */  OCAML_ACC0,
  /*  12 */  OCAML_C_CALL1, 1,
  /*  14 */  OCAML_PUSHACC2,
  /*  15 */  OCAML_C_CALL1, 1,
  /*  17 */  OCAML_PUSH,
  /*  18 */  OCAML_PUSHACC2,
  /*  19 */  OCAML_ADDINT,
  /*  20 */  OCAML_C_CALL1, 2,
  /*  22 */  OCAML_PUSHACC2,
  /*  23 */  OCAML_PUSHCONST0,
  /*  24 */  OCAML_PUSHACC2,
  /*  25 */  OCAML_PUSHCONST0,
  /*  26 */  OCAML_PUSHACC7,
  /*  27 */  OCAML_C_CALL5, 3,
  /*  29 */  OCAML_ACC1,
  /*  30 */  OCAML_PUSHACC3,
  /*  31 */  OCAML_PUSHACC2,
  /*  32 */  OCAML_PUSHCONST0,
  /*  33 */  OCAML_PUSHACC, 8,
  /*  35 */  OCAML_C_CALL5, 3,
  /*  37 */  OCAML_ACC0,
  /*  38 */  OCAML_C_CALL1, 4,
  /*  40 */  OCAML_RETURN, 5,
  /*  42 */  OCAML_ACC0,
  /*  43 */  OCAML_PUSHGETFLASHGLOBAL_1B, 0,
  /*  45 */  OCAML_MAKEBLOCK2, 0,
  /*  47 */  OCAML_RAISE,
  /*  48 */  OCAML_ACC0,
  /*  49 */  OCAML_C_CALL1, 5,
  /*  51 */  OCAML_RETURN, 1,
  /*  53 */  OCAML_ACC0,
  /*  54 */  OCAML_C_CALL1, 6,
  /*  56 */  OCAML_RETURN, 1,
  /*  58 */  OCAML_RESTART,
  /*  59 */  OCAML_GRAB, 2,
  /*  61 */  OCAML_ACC1,
  /*  62 */  OCAML_BGTINT_1B, 0, 16,
  /*  65 */  OCAML_ACC2,
  /*  66 */  OCAML_BGTINT_1B, 0, 12,
  /*  69 */  OCAML_ACC2,
  /*  70 */  OCAML_PUSHACC1,
  /*  71 */  OCAML_C_CALL1, 7,
  /*  73 */  OCAML_SUBINT,
  /*  74 */  OCAML_PUSHACC2,
  /*  75 */  OCAML_GTINT,
  /*  76 */  OCAML_BRANCHIFNOT_1B, 8,
  /*  78 */  OCAML_GETFLASHGLOBAL_1B, 1,
  /*  80 */  OCAML_PUSHGETFLASHGLOBAL_1B, 2,
  /*  82 */  OCAML_APPTERM1, 4,
  /*  84 */  OCAML_ACC2,
  /*  85 */  OCAML_C_CALL1, 2,
  /*  87 */  OCAML_PUSHACC3,
  /*  88 */  OCAML_PUSHCONST0,
  /*  89 */  OCAML_PUSHACC2,
  /*  90 */  OCAML_PUSHACC5,
  /*  91 */  OCAML_PUSHACC5,
  /*  92 */  OCAML_C_CALL5, 8,
  /*  94 */  OCAML_ACC0,
  /*  95 */  OCAML_RETURN, 4,
  /*  97 */  OCAML_ACC0,
  /*  98 */  OCAML_PUSHGETFLASHGLOBAL_1B, 3,
  /* 100 */  OCAML_APPLY1,
  /* 101 */  OCAML_C_CALL1, 5,
  /* 103 */  OCAML_RETURN, 1,
  /* 105 */  OCAML_ACC0,
  /* 106 */  OCAML_C_CALL1, 7,
  /* 108 */  OCAML_PUSH,
  /* 109 */  OCAML_C_CALL1, 2,
  /* 111 */  OCAML_PUSHACC1,
  /* 112 */  OCAML_PUSHCONST0,
  /* 113 */  OCAML_PUSHACC2,
  /* 114 */  OCAML_PUSHCONST0,
  /* 115 */  OCAML_PUSHACC6,
  /* 116 */  OCAML_C_CALL5, 8,
  /* 118 */  OCAML_ACC0,
  /* 119 */  OCAML_RETURN, 3,
  /* 121 */  OCAML_RESTART,
  /* 122 */  OCAML_GRAB, 1,
  /* 124 */  OCAML_ACC0,
  /* 125 */  OCAML_C_CALL1, 2,
  /* 127 */  OCAML_PUSHACC2,
  /* 128 */  OCAML_PUSHACC2,
  /* 129 */  OCAML_PUSHCONST0,
  /* 130 */  OCAML_PUSHACC3,
  /* 131 */  OCAML_C_CALL4, 9,
  /* 133 */  OCAML_ACC0,
  /* 134 */  OCAML_RETURN, 3,
  /* 136 */  OCAML_RESTART,
  /* 137 */  OCAML_GRAB, 1,
  /* 139 */  OCAML_CONST0,
  /* 140 */  OCAML_PUSHACC2,
  /* 141 */  OCAML_C_CALL1, 1,
  /* 143 */  OCAML_OFFSETINT_1B, (opcode_t) -1,
  /* 145 */  OCAML_PUSH,
  /* 146 */  OCAML_PUSHACC2,
  /* 147 */  OCAML_GTINT,
  /* 148 */  OCAML_BRANCHIF_1B, 19,
  /* 150 */  OCAML_CHECK_SIGNALS,
  /* 151 */  OCAML_ACC1,
  /* 152 */  OCAML_PUSHACC4,
  /* 153 */  OCAML_GETBYTESCHAR,
  /* 154 */  OCAML_PUSHACC2,
  /* 155 */  OCAML_PUSHACC4,
  /* 156 */  OCAML_APPLY2,
  /* 157 */  OCAML_ACC1,
  /* 158 */  OCAML_PUSH,
  /* 159 */  OCAML_OFFSETINT_1B, 1,
  /* 161 */  OCAML_ASSIGN, 2,
  /* 163 */  OCAML_ACC1,
  /* 164 */  OCAML_NEQ,
  /* 165 */  OCAML_BRANCHIF_1B, (opcode_t) -15,
  /* 167 */  OCAML_CONST0,
  /* 168 */  OCAML_RETURN, 4,
  /* 170 */  OCAML_RESTART,
  /* 171 */  OCAML_GRAB, 1,
  /* 173 */  OCAML_CONST0,
  /* 174 */  OCAML_PUSHACC2,
  /* 175 */  OCAML_C_CALL1, 1,
  /* 177 */  OCAML_OFFSETINT_1B, (opcode_t) -1,
  /* 179 */  OCAML_PUSH,
  /* 180 */  OCAML_PUSHACC2,
  /* 181 */  OCAML_GTINT,
  /* 182 */  OCAML_BRANCHIF_1B, 18,
  /* 184 */  OCAML_CHECK_SIGNALS,
  /* 185 */  OCAML_ACC1,
  /* 186 */  OCAML_PUSHACC4,
  /* 187 */  OCAML_GETBYTESCHAR,
  /* 188 */  OCAML_PUSHACC3,
  /* 189 */  OCAML_APPLY1,
  /* 190 */  OCAML_ACC1,
  /* 191 */  OCAML_PUSH,
  /* 192 */  OCAML_OFFSETINT_1B, 1,
  /* 194 */  OCAML_ASSIGN, 2,
  /* 196 */  OCAML_ACC1,
  /* 197 */  OCAML_NEQ,
  /* 198 */  OCAML_BRANCHIF_1B, (opcode_t) -14,
  /* 200 */  OCAML_CONST0,
  /* 201 */  OCAML_RETURN, 4,
  /* 203 */  OCAML_RESTART,
  /* 204 */  OCAML_GRAB, 2,
  /* 206 */  OCAML_ACC2,
  /* 207 */  OCAML_PUSHACC2,
  /* 208 */  OCAML_PUSHACC2,
  /* 209 */  OCAML_PUSHGETFLASHGLOBAL_1B, 4,
  /* 211 */  OCAML_APPLY1,
  /* 212 */  OCAML_PUSHGETFLASHGLOBAL_1B, 5,
  /* 214 */  OCAML_APPLY3,
  /* 215 */  OCAML_PUSHGETFLASHGLOBAL_1B, 6,
  /* 217 */  OCAML_APPTERM1, 4,
  /* 219 */  OCAML_RESTART,
  /* 220 */  OCAML_GRAB, 1,
  /* 222 */  OCAML_ACC1,
  /* 223 */  OCAML_PUSHACC1,
  /* 224 */  OCAML_PUSHGETFLASHGLOBAL_1B, 7,
  /* 226 */  OCAML_APPLY2,
  /* 227 */  OCAML_PUSHGETFLASHGLOBAL_1B, 6,
  /* 229 */  OCAML_APPTERM1, 3,
  /* 231 */  OCAML_RESTART,
  /* 232 */  OCAML_GRAB, 1,
  /* 234 */  OCAML_ACC1,
  /* 235 */  OCAML_BRANCHIFNOT_1B, 12,
  /* 237 */  OCAML_ACC1,
  /* 238 */  OCAML_GETFIELD0,
  /* 239 */  OCAML_PUSHACC1,
  /* 240 */  OCAML_APPLY1,
  /* 241 */  OCAML_ACC1,
  /* 242 */  OCAML_GETFIELD1,
  /* 243 */  OCAML_PUSHACC1,
  /* 244 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 245 */  OCAML_APPTERM2, 4,
  /* 247 */  OCAML_RETURN, 2,
  /* 249 */  OCAML_ACC0,
  /* 250 */  OCAML_C_CALL1, 10,
  /* 252 */  OCAML_RETURN, 1,
  /* 254 */  OCAML_ACC0,
  /* 255 */  OCAML_PUSHGETFLASHGLOBAL_1B, 8,
  /* 257 */  OCAML_APPLY1,
  /* 258 */  OCAML_PUSHGETFLASHGLOBAL_1B, 9,
  /* 260 */  OCAML_APPTERM1, 2,
  /* 262 */  OCAML_RESTART,
  /* 263 */  OCAML_GRAB, 1,
  /* 265 */  OCAML_ACC1,
  /* 266 */  OCAML_PUSHACC1,
  /* 267 */  OCAML_PUSHENVACC1,
  /* 268 */  OCAML_SUBINT,
  /* 269 */  OCAML_OFFSETINT_1B, (opcode_t) -1,
  /* 271 */  OCAML_C_CALL2, 11,
  /* 273 */  OCAML_RETURN, 2,
  /* 275 */  OCAML_ACC0,
  /* 276 */  OCAML_PUSHCONSTINT_1B, 6,
  /* 278 */  OCAML_PUSHGETFLASHGLOBAL_1B, 10,
  /* 280 */  OCAML_APPLY2,
  /* 281 */  OCAML_PUSHCONSTINT_1B, 6,
  /* 283 */  OCAML_CLOSURE_1B, 1, (opcode_t) -20,
  /* 286 */  OCAML_PUSHGETFLASHGLOBAL_1B, 11,
  /* 288 */  OCAML_APPTERM2, 3,
  /* 290 */  OCAML_RESTART,
  /* 291 */  OCAML_GRAB, 1,
  /* 293 */  OCAML_ACC1,
  /* 294 */  OCAML_C_CALL1, 1,
  /* 296 */  OCAML_PUSHACC1,
  /* 297 */  OCAML_PUSHACC1,
  /* 298 */  OCAML_LTINT,
  /* 299 */  OCAML_BRANCHIFNOT_1B, 15,
  /* 301 */  OCAML_CONSTINT_1B, 32,
  /* 303 */  OCAML_PUSHACC1,
  /* 304 */  OCAML_PUSHACC3,
  /* 305 */  OCAML_SUBINT,
  /* 306 */  OCAML_PUSHGETFLASHGLOBAL_1B, 12,
  /* 308 */  OCAML_APPLY2,
  /* 309 */  OCAML_PUSHACC3,
  /* 310 */  OCAML_PUSHGETFLASHGLOBAL_1B, 13,
  /* 312 */  OCAML_APPTERM2, 5,
  /* 314 */  OCAML_ACC1,
  /* 315 */  OCAML_PUSHACC1,
  /* 316 */  OCAML_GTINT,
  /* 317 */  OCAML_BRANCHIFNOT_1B, 9,
  /* 319 */  OCAML_ACC1,
  /* 320 */  OCAML_PUSHCONST0,
  /* 321 */  OCAML_PUSHACC4,
  /* 322 */  OCAML_PUSHGETFLASHGLOBAL_1B, 14,
  /* 324 */  OCAML_APPTERM3, 6,
  /* 326 */  OCAML_ACC2,
  /* 327 */  OCAML_RETURN, 3,
  /* 329 */  OCAML_ACC0,
  /* 330 */  OCAML_PUSHGETFLASHGLOBAL_1B, 8,
  /* 332 */  OCAML_APPLY1,
  /* 333 */  OCAML_PUSHGETFLASHGLOBAL_1B, 15,
  /* 335 */  OCAML_APPTERM1, 2,
  /* 337 */  OCAML_CONST0,
  /* 338 */  OCAML_PUSHCONST0,
  /* 339 */  OCAML_PUSHGETFLASHGLOBAL_1B, 16,
  /* 341 */  OCAML_APPLY2,
  /* 342 */  OCAML_PUSHGETFLASHGLOBAL_1B, 17,
  /* 344 */  OCAML_APPTERM1, 2,
  /* 346 */  OCAML_RESTART,
  /* 347 */  OCAML_GRAB, 1,
  /* 349 */  OCAML_ENVACC1,
  /* 350 */  OCAML_C_CALL1, 1,
  /* 352 */  OCAML_PUSHACC1,
  /* 353 */  OCAML_LTINT,
  /* 354 */  OCAML_BRANCHIFNOT_1B, 32,
  /* 356 */  OCAML_ACC0,
  /* 357 */  OCAML_PUSHENVACC1,
  /* 358 */  OCAML_C_CALL2, 12,
  /* 360 */  OCAML_PUSH,
  /* 361 */  OCAML_BGTINT_1B, 48, 22,
  /* 364 */  OCAML_ACC0,
  /* 365 */  OCAML_BLTINT_1B, 57, 18,
  /* 368 */  OCAML_CONSTINT_1B, 48,
  /* 370 */  OCAML_PUSHACC1,
  /* 371 */  OCAML_PUSHCONSTINT_1B, 10,
  /* 373 */  OCAML_PUSHACC5,
  /* 374 */  OCAML_MULINT,
  /* 375 */  OCAML_ADDINT,
  /* 376 */  OCAML_SUBINT,
  /* 377 */  OCAML_PUSHACC2,
  /* 378 */  OCAML_OFFSETINT_1B, 1,
  /* 380 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 381 */  OCAML_APPTERM2, 5,
  /* 383 */  OCAML_ACC2,
  /* 384 */  OCAML_RETURN, 3,
  /* 386 */  OCAML_ACC1,
  /* 387 */  OCAML_RETURN, 2,
  /* 389 */  OCAML_ACC0,
  /* 390 */  OCAML_CLOSUREREC_1B, 1, 1, (opcode_t) -43,
  /* 394 */  OCAML_CONST0,
  /* 395 */  OCAML_PUSHCONST0,
  /* 396 */  OCAML_PUSHACC2,
  /* 397 */  OCAML_APPTERM2, 4,
  /* 399 */  OCAML_CONST0,
  /* 400 */  OCAML_C_CALL1, 13,
  /* 402 */  OCAML_PUSHENVACC1,
  /* 403 */  OCAML_PUSHACC1,
  /* 404 */  OCAML_NEQ,
  /* 405 */  OCAML_BRANCHIFNOT_1B, 18,
  /* 407 */  OCAML_ENVACC2,
  /* 408 */  OCAML_PUSHACC2,
  /* 409 */  OCAML_LTINT,
  /* 410 */  OCAML_BRANCHIFNOT_1B, 13,
  /* 412 */  OCAML_ACC0,
  /* 413 */  OCAML_PUSHACC2,
  /* 414 */  OCAML_PUSHENVACC3,
  /* 415 */  OCAML_C_CALL3, 14,
  /* 417 */  OCAML_ACC1,
  /* 418 */  OCAML_OFFSETINT_1B, 1,
  /* 420 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 421 */  OCAML_APPTERM1, 3,
  /* 423 */  OCAML_ENVACC3,
  /* 424 */  OCAML_RETURN, 2,
  /* 426 */  OCAML_RESTART,
  /* 427 */  OCAML_GRAB, 1,
  /* 429 */  OCAML_ACC0,
  /* 430 */  OCAML_BRANCHIFNOT_1B, 6,
  /* 432 */  OCAML_ACC0,
  /* 433 */  OCAML_GETFIELD0,
  /* 434 */  OCAML_BRANCH_1B, 4,
  /* 436 */  OCAML_CONSTINT_1B, 10,
  /* 438 */  OCAML_PUSHCONSTINT_1B, 32,
  /* 440 */  OCAML_PUSH,
  /* 441 */  OCAML_C_CALL1, 2,
  /* 443 */  OCAML_PUSH,
  /* 444 */  OCAML_PUSHACC2,
  /* 445 */  OCAML_PUSHACC4,
  /* 446 */  OCAML_CLOSUREREC_1B, 1, 3, (opcode_t) -47,
  /* 450 */  OCAML_CONST0,
  /* 451 */  OCAML_PUSHACC1,
  /* 452 */  OCAML_APPLY1,
  /* 453 */  OCAML_PUSHGETFLASHGLOBAL_1B, 18,
  /* 455 */  OCAML_APPTERM1, 7,
  /* 457 */  OCAML_ACC0,
  /* 458 */  OCAML_C_CALL1, 15,
  /* 460 */  OCAML_RETURN, 1,
  /* 462 */  OCAML_ACC0,
  /* 463 */  OCAML_PUSH,
  /* 464 */  OCAML_CLOSURE_1B, 0, (opcode_t) -7,
  /* 467 */  OCAML_PUSHGETFLASHGLOBAL_1B, 19,
  /* 469 */  OCAML_APPTERM2, 3,
  /* 471 */  OCAML_RESTART,
  /* 472 */  OCAML_GRAB, 1,
  /* 474 */  OCAML_ACC1,
  /* 475 */  OCAML_PUSHACC1,
  /* 476 */  OCAML_EQ,
  /* 477 */  OCAML_BRANCHIFNOT_1B, 5,
  /* 479 */  OCAML_ACC0,
  /* 480 */  OCAML_RETURN, 2,
  /* 482 */  OCAML_ACC1,
  /* 483 */  OCAML_PUSHACC1,
  /* 484 */  OCAML_GTINT,
  /* 485 */  OCAML_BRANCHIFNOT_1B, 9,
  /* 487 */  OCAML_ACC1,
  /* 488 */  OCAML_PUSHACC2,
  /* 489 */  OCAML_PUSHACC2,
  /* 490 */  OCAML_SUBINT,
  /* 491 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 492 */  OCAML_APPTERM2, 4,
  /* 494 */  OCAML_ACC0,
  /* 495 */  OCAML_PUSHACC2,
  /* 496 */  OCAML_SUBINT,
  /* 497 */  OCAML_PUSHACC1,
  /* 498 */  OCAML_PUSHOFFSETCLOSURE0,
  /* 499 */  OCAML_APPTERM2, 4,
  /* 501 */  OCAML_RESTART,
  /* 502 */  OCAML_GRAB, 1,
  /* 504 */  OCAML_ACC1,
  /* 505 */  OCAML_PUSHACC1,
  /* 506 */  OCAML_C_CALL2, 16,
  /* 508 */  OCAML_RETURN, 2,
  /* 510 */  OCAML_RESTART,
  /* 511 */  OCAML_GRAB, 1,
  /* 513 */  OCAML_ACC1,
  /* 514 */  OCAML_PUSHACC1,
  /* 515 */  OCAML_C_CALL2, 17,
  /* 517 */  OCAML_RETURN, 2,
  /* 519 */  OCAML_RESTART,
  /* 520 */  OCAML_GRAB, 1,
  /* 522 */  OCAML_ACC1,
  /* 523 */  OCAML_PUSHACC1,
  /* 524 */  OCAML_C_CALL2, 18,
  /* 526 */  OCAML_RETURN, 2,
  /* 528 */  OCAML_CONST0,
  /* 529 */  OCAML_C_CALL1, 19,
  /* 531 */  OCAML_PUSHCONSTINT_4B, 0, 7, 161, 61,
  /* 536 */  OCAML_PUSHCONSTINT_4B, 0, 7, 161, 41,
  /* 541 */  OCAML_PUSHACC3,
  /* 542 */  OCAML_APPLY2,
  /* 543 */  OCAML_PUSHCONST0,
  /* 544 */  OCAML_C_CALL1, 19,
  /* 546 */  OCAML_PUSHACC2,
  /* 547 */  OCAML_PUSHACC1,
  /* 548 */  OCAML_SUBINT,
  /* 549 */  OCAML_PUSHACC2,
  /* 550 */  OCAML_MAKEBLOCK2, 0,
  /* 552 */  OCAML_RETURN, 4,
  /* 554 */  OCAML_GETFLASHGLOBAL_1B, 20,
  /* 556 */  OCAML_PUSHACC1,
  /* 557 */  OCAML_PUSHGETFLASHGLOBAL_1B, 13,
  /* 559 */  OCAML_APPLY2,
  /* 560 */  OCAML_PUSHGETFLASHGLOBAL_1B, 21,
  /* 562 */  OCAML_GETFIELD1,
  /* 563 */  OCAML_APPLY1,
  /* 564 */  OCAML_GETFLASHGLOBAL_1B, 22,
  /* 566 */  OCAML_RAISE,
  /* 567 */  OCAML_ACC0,
  /* 568 */  OCAML_PUSHGETFLASHGLOBAL_1B, 21,
  /* 570 */  OCAML_GETFIELD0,
  /* 571 */  OCAML_APPLY1,
  /* 572 */  OCAML_GETFLASHGLOBAL_1B, 23,
  /* 574 */  OCAML_PUSHGETFLASHGLOBAL_1B, 21,
  /* 576 */  OCAML_GETFIELD1,
  /* 577 */  OCAML_APPTERM1, 2,
  /* 579 */  OCAML_ACC0,
  /* 580 */  OCAML_PUSH,
  /* 581 */  OCAML_CLOSURE_1B, 0, (opcode_t) -14,
  /* 584 */  OCAML_PUSHGETFLASHGLOBAL_1B, 24,
  /* 586 */  OCAML_APPLY2,
  /* 587 */  OCAML_GETFLASHGLOBAL_1B, 25,
  /* 589 */  OCAML_PUSHGETFLASHGLOBAL_1B, 21,
  /* 591 */  OCAML_GETFIELD1,
  /* 592 */  OCAML_APPTERM1, 2,
  /* 594 */  OCAML_ACC0,
  /* 595 */  OCAML_PUSHGETFLASHGLOBAL_1B, 26,
  /* 597 */  OCAML_GETFIELD2,
  /* 598 */  OCAML_APPLY1,
  /* 599 */  OCAML_CONSTINT_1B, 100,
  /* 601 */  OCAML_PUSHGETFLASHGLOBAL_1B, 27,
  /* 603 */  OCAML_APPTERM1, 2,
  /* 605 */  OCAML_C_CALL1, 20,
  /* 607 */  OCAML_CONST0,
  /* 608 */  OCAML_C_CALL1, 21,
  /* 610 */  OCAML_PUSHCONST0,
  /* 611 */  OCAML_GTINT,
  /* 612 */  OCAML_BRANCHIFNOT_1B, 6,
  /* 614 */  OCAML_GETFLASHGLOBAL_1B, 28,
  /* 616 */  OCAML_PUSHACC2,
  /* 617 */  OCAML_APPLY1,
  /* 618 */  OCAML_BRANCH_1B, 86,
  /* 620 */  OCAML_CHECK_SIGNALS,
  /* 621 */  OCAML_ACC4,
  /* 622 */  OCAML_PUSHACC1,
  /* 623 */  OCAML_APPLY1,
  /* 624 */  OCAML_PUSH,
  /* 625 */  OCAML_GETFIELD1,
  /* 626 */  OCAML_PUSHACC1,
  /* 627 */  OCAML_GETFIELD0,
  /* 628 */  OCAML_PUSH,
  /* 629 */  OCAML_CLOSURE_1B, 0, (opcode_t) -109,
  /* 632 */  OCAML_PUSHACC4,
  /* 633 */  OCAML_APPLY1,
  /* 634 */  OCAML_PUSH,
  /* 635 */  OCAML_GETFIELD1,
  /* 636 */  OCAML_PUSHACC1,
  /* 637 */  OCAML_GETFIELD0,
  /* 638 */  OCAML_PUSH,
  /* 639 */  OCAML_CLOSURE_1B, 0, (opcode_t) -128,
  /* 642 */  OCAML_PUSHACC7,
  /* 643 */  OCAML_APPLY1,
  /* 644 */  OCAML_PUSH,
  /* 645 */  OCAML_GETFIELD1,
  /* 646 */  OCAML_PUSHACC1,
  /* 647 */  OCAML_GETFIELD0,
  /* 648 */  OCAML_PUSH,
  /* 649 */  OCAML_CLOSURE_2B, 0, (opcode_t) -1, 109,
  /* 653 */  OCAML_PUSHACC, 10,
  /* 655 */  OCAML_APPLY1,
  /* 656 */  OCAML_PUSH,
  /* 657 */  OCAML_GETFIELD1,
  /* 658 */  OCAML_PUSHACC1,
  /* 659 */  OCAML_GETFIELD0,
  /* 660 */  OCAML_PUSHCONST0,
  /* 661 */  OCAML_PUSHACC2,
  /* 662 */  OCAML_MAKEBLOCK2, 0,
  /* 664 */  OCAML_PUSHACC5,
  /* 665 */  OCAML_MAKEBLOCK2, 0,
  /* 667 */  OCAML_PUSHACC, 8,
  /* 669 */  OCAML_MAKEBLOCK2, 0,
  /* 671 */  OCAML_PUSHACC, 11,
  /* 673 */  OCAML_MAKEBLOCK2, 0,
  /* 675 */  OCAML_PUSHACC, 15,
  /* 677 */  OCAML_APPLY1,
  /* 678 */  OCAML_ACC, 9,
  /* 680 */  OCAML_PUSHACC1,
  /* 681 */  OCAML_SUBINT,
  /* 682 */  OCAML_PUSHCONSTINT_1B, 10,
  /* 684 */  OCAML_PUSHACC, 11,
  /* 686 */  OCAML_PUSHACC6,
  /* 687 */  OCAML_SUBINT,
  /* 688 */  OCAML_MULINT,
  /* 689 */  OCAML_PUSHCONSTINT_1B, 100,
  /* 691 */  OCAML_PUSHACC, 12,
  /* 693 */  OCAML_PUSHACC, 10,
  /* 695 */  OCAML_SUBINT,
  /* 696 */  OCAML_MULINT,
  /* 697 */  OCAML_ADDINT,
  /* 698 */  OCAML_ADDINT,
  /* 699 */  OCAML_PUSHACC, 16,
  /* 701 */  OCAML_APPLY1,
  /* 702 */  OCAML_POP, 12,
  /* 704 */  OCAML_CONST1,
  /* 705 */  OCAML_BRANCHIF_1B, (opcode_t) -85,
  /* 707 */  OCAML_POP, 5,
  /* 709 */  OCAML_STOP
};

#include </media/sf_SF2/ml/O2B/omicrob/include/vm/runtime.c>

PROGMEM void * const ocaml_primitives[OCAML_PRIMITIVE_NUMBER] = {
  /*  0 */  (void *) &caml_string_of_int,
  /*  1 */  (void *) &caml_ml_string_length,
  /*  2 */  (void *) &caml_create_bytes,
  /*  3 */  (void *) &caml_blit_string,
  /*  4 */  (void *) &caml_string_of_bytes,
  /*  5 */  (void *) &caml_unsafe_string_of_bytes,
  /*  6 */  (void *) &caml_unsafe_bytes_of_string,
  /*  7 */  (void *) &caml_ml_bytes_length,
  /*  8 */  (void *) &caml_blit_bytes,
  /*  9 */  (void *) &caml_fill_bytes,
  /* 10 */  (void *) &caml_delay,
  /* 11 */  (void *) &caml_nios_ssd_display_char,
  /* 12 */  (void *) &caml_string_get,
  /* 13 */  (void *) &caml_nios_serial_read_char,
  /* 14 */  (void *) &caml_bytes_set,
  /* 15 */  (void *) &caml_nios_serial_write_char,
  /* 16 */  (void *) &caml_nios_gcd_cc,
  /* 17 */  (void *) &caml_nios_gcd_ci,
  /* 18 */  (void *) &caml_nios_gcd,
  /* 19 */  (void *) &caml_nios_timer_get_us,
  /* 20 */  (void *) &caml_nios_get_sys_id,
  /* 21 */  (void *) &caml_nios_timer_init,
};
