//#include <stdio.h>
/* #include <sys/alt_driver.h> */
#include <sys/alt_stdio.h>
/* #include <priv/alt_file.h> */
#include <unistd.h> // For usleep
#include "sys/alt_timestamp.h" 
#include "sys/alt_alarm.h"  // For alt_nticks()
//#include <sys/times.h> // For times()
#include "alt_types.h"
#include "altera_avalon_pio_regs.h"
#include "altera_avalon_sysid_qsys_regs.h"
#include "system.h"  // BSP description generated by nios-bsp and located in <project>/bsp

void nios_serial_write_char(char c)
{
  alt_printf("%c", c);
}

void nios_serial_write_string(char* s)
{
  alt_printf(s);
}

char nios_serial_read_char()
{
  return alt_getchar();
}

static struct {
  unsigned long ticks_per_us;
  unsigned long ticks_per_ms;
} nios_timer_spec;

int nios_timer_init()
{
  int r = alt_timestamp_start();
  unsigned long ticks_per_sec = alt_timestamp_freq();
  nios_timer_spec.ticks_per_ms = ticks_per_sec / 1000;  // Pre-compute these values for limiting the RT overhead
  nios_timer_spec.ticks_per_us = ticks_per_sec / 1000000;
  return r;
}

int nios_timer_get_us()
{
  unsigned long t = alt_timestamp() / nios_timer_spec.ticks_per_us;
  return t;
}

int nios_timer_get_ms()
{
  unsigned long t = alt_timestamp() / nios_timer_spec.ticks_per_ms;
  return t;
}

void delay(int ms) { usleep(ms*1000); } 

#define TPS_SCALE_FACTOR 694 // To be adjusted

int millis()
{
  alt_u32 t = alt_nticks();
  return t*TPS_SCALE_FACTOR/alt_ticks_per_second();
}
