//#include <stdio.h>
/* #include <sys/alt_driver.h> */
#include <sys/alt_stdio.h>
/* #include <priv/alt_file.h> */
#include <unistd.h> // For usleep
#include "sys/alt_timestamp.h" 
#include "sys/alt_alarm.h"  // For alt_nticks()
//#include <sys/times.h> // For times()
#include "alt_types.h"
#include "altera_avalon_pio_regs.h"
#include "altera_avalon_sysid_qsys_regs.h"
#include "system.h"  // BSP description generated by nios-bsp and located in <project>/bsp

void nios_serial_write_char(char c)
{
  alt_printf("%c", c);
}

void nios_serial_write_string(char* s)
{
  alt_printf(s);
}

char nios_serial_read_char()
{
  return alt_getchar();
}

static struct {
  unsigned long ticks_per_us;
  unsigned long ticks_per_ms;
} nios_timer_spec;

int nios_timer_init()
{
  int r = alt_timestamp_start();
  unsigned long ticks_per_sec = alt_timestamp_freq();
  nios_timer_spec.ticks_per_ms = ticks_per_sec / 1000;  // Pre-compute these values for limiting the RT overhead
  nios_timer_spec.ticks_per_us = ticks_per_sec / 1000000;
  return r;
}

int nios_timer_get_us()
{
  unsigned long t = alt_timestamp() / nios_timer_spec.ticks_per_us;
  return t;
}

int nios_timer_get_ms()
{
  unsigned long t = alt_timestamp() / nios_timer_spec.ticks_per_ms;
  return t;
}

void delay(int ms) { usleep(ms*1000); } 

#define TPS_SCALE_FACTOR 694 // To be adjusted

int millis()
{
  alt_u32 t = alt_nticks();
  return t*TPS_SCALE_FACTOR/alt_ticks_per_second();
}

// Extended functions

#define REDUCE_INIT 0
#define REDUCE_FUN(x,y) ((x)+(y))

#ifdef __OCAML__
#include <caml/mlvalues.h>
#else
#include "vm/values.h"
#endif

int nios_list_reduce(uint32_t v)
{
  int32_t acc = 0;
  while ( Is_block(v) ) {
    acc += Int_val(Field(v,0));
    v = Field(v,1);
    }
  return acc;
}

int nios_list_reduce_cc(uint32_t v)
{
  int arg1, arg2, res1, res2;

  // INVOKE CUSTOM COMPONENT
  // The code is given in ../rtl/list_reduce.vhd

  IOWR(LRED_CC_0_BASE, 1, ocaml_ram_heap); 
  IOWR(LRED_CC_0_BASE, 2, v); 
  IOWR(LRED_CC_0_BASE, 0, 1);  // Writing control/status register starts operation
  while ( IORD(LRED_CC_0_BASE, 0) == 0 ); // Wait for rdy
  arg1 = IORD(LRED_CC_0_BASE, 1);
  arg2 = IORD(LRED_CC_0_BASE, 2);
  res1 = IORD(LRED_CC_0_BASE, 3);
  res2 = IORD(LRED_CC_0_BASE, 4);
  // alt_printf("** nios_list_reduce_cc: arg1=%x\n", arg1);
  // alt_printf("** nios_list_reduce_cc: arg2=%x\n", arg2);
  // alt_printf("** nios_list_reduce_cc: res=%x/%x\n", res1, res2);
  return res1;
}
